# fly.toml app configuration file generated for maksymilian-org-strapi on 2023-06-14T12:35:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "maksymilian-org-strapi"
primary_region = "waw"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
